name: bimbo_delivery
description: Bimbo delivery app


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_localizations:
    sdk: flutter

  dio: ^4.0.6
  http: ^0.13.4
  loading:
    git: https://github.com/bradintheusa/loading
  record: ^3.0.4
  provider: ^6.0.2
  path_provider: ^2.0.9
  flutter_easyloading: ^3.0.3
  speech_to_text: ^5.6.0
  audioplayers: ^0.20.1
  cool_alert: ^1.1.0
  permission_handler: ^10.0.0
  external_path: ^1.0.1
  http_parser: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/

